elementary/panel-datetime

src/Services/TimeManager.vala

Fixes #3 and fixes #16 .
To resolve the time not being updated when the settings are being changed, the indicator watches the D-BUS daemon that is associated with the time settings. It only runs when the settings are being changed. While running, the indicator updates its time more frequently.
The time being slow to update after waking from sleep was due to the fact that the timeout is calculated based upon the number of seconds until the minute changes.
If you put the computer to sleep 15 seconds after the minute has changed, it will take 45 seconds after waking for the clock to update. This is also the cause of the difference between the wingpanel time and the system time.
This branch resolves both of these issue by triggering an update as soon as the system wakes from sleep and …

Update time on settings change and awake from sleep

---

src/Widgets/calendar/Calendar.vala
src/Widgets/calendar/Grid.vala
src/Widgets/calendar/GridDay.vala
src/Widgets/calendar/Header.vala
src/Widgets/calendar/WeekLabels.vala

Replaces a bunch of unsavory Cairo with a little bit of Gtk.CSS
Fixes #20

Replace cairo with Gtk.CSS

---

src/Indicator.vala

Fixed the non expanding gtk container when the label is dynamically wrapping too long text. So now long Labels will show just fine and the settings down below won't disappear because the popover is automatically resized

Fix #51: Missing Gtk Alignment in main Indicator container

---

CMakeLists.txt
config.vala.cmake
src/CMakeLists.txt

None of these constants are used

Remove unused config.vala

---

src/Widgets/PanelLabel.vala

I fixed URL links of GLib.DateTime.format in Valadoc.
The old one may be dead links.

Fixed links of GLib.DateTime.format in Valadoc

---

src/Widgets/calendar/CalendarView.vala
src/Widgets/calendar/Grid.vala
src/Widgets/calendar/GridDay.vala

Fixes #76. This separates the concerns of a focused date versus today, which could help reduce the confusion I've had in the indicator.

Remove the explicit refocus

---

src/Services/TimeManager.vala
src/Widgets/PanelLabel.vala

Supersedes #53 
Fixes #40 
* Use Granite.DateTime instead of managing clock format translations ourselves
* Listen for the `clock-show-seconds` dconf key and respect it

Listen to option for showing seconds

---

src/Widgets/calendar/CalendarView.vala
src/Widgets/calendar/Grid.vala
src/Widgets/calendar/GridDay.vala

Selects / focuses in on today when opened. 
Fixes: https://github.com/elementary/wingpanel-indicator-datetime/issues/102

Focus today on opened

---

po/nb.po
src/Indicator.vala
src/Widgets/calendar/CalendarView.vala

Fixes #105 
By resetting selected_date.
Events are otherwise not cleared when navigating between months.

Reset events on month change

---

src/Widgets/calendar/Calendar.vala

Fixes #116 
Throws a dialog on error instead of leaving users in the dark:

Calendar: don't use absolute path or error silently

---

src/Widgets/calendar/CalendarModel.vala

We have two license headers, one version 2 and one version 3. Since version 2 says we can distribute under later versions of the GPL, let's go with just 3

CalendarModel: Remove extra license

---

src/Widgets/calendar/Calendar.vala
src/Widgets/calendar/ControlHeader.vala

* Subclass Gtk.Grid instead of Box
* Fix `selected_date`
* Explicitly scope variables
* GObject-style construction
* Remove useless properties
* Organize

Calendar: GObject-style

---

src/Event.vala
src/Indicator.vala

Instead of not showing via their labels, make shown:
- All-Day events
- Alarms
- End times of events that span times

Make event labels smarter

---

src/Event.vala
src/Widgets/EventRow.vala

Seems silly to have this method since component is already public and this does nothing but return get_summary

Event: Remove get_event_label

---

src/Widgets/calendar/CalendarModel.vala
src/Widgets/calendar/CalendarView.vala

Since we're ignoring when anything other than data_range changes, listen to that directly
Also, don't listen to the same signal twice

CalendarView: listen specifically for datarange and simplify

---

.github/workflows/release.yml

Changes: 
* add new release process action
Requires `GIT_USER_TOKEN` secret to be set on the project.

Add release ci action

---

data/datetime.appdata.xml.in
src/Widgets/calendar/Grid.vala
src/Widgets/calendar/GridDay.vala

Based on an idea from @Dirli and #216 by @ikarosdev
This greatly reduces the number of connections to the calendar model and noticeably improves performance when switching months
"Hide Whitespace Changes" to show that the only real changes in GridDay are deletions.

Grid: Fewer CalendarModel connections

---

src/Indicator.vala

Noticed this in https://github.com/elementary/greeter/pull/450 https://github.com/elementary/greeter/pull/450#issuecomment-655130041. I tested that this indicator doesn't show in the greeter now in a vm.

Prevent loading DateTime outside session

---

src/Widgets/calendar/Util.vala

Updated `timezone_from_ical` to do the same thing as `icaltime_get_timezone` in Calendar. This Fixes #59

Calculate TimeZone according to Calendar

---

data/EventRow.css
src/Widgets/EventRow.vala

Combined with https://github.com/elementary/stylesheet/pull/852 , relies on the theme for background and foreground colors. Fixes issues with dark style

EventRow: Rely on stylesheet for colors

---

src/Widgets/calendar/CalendarView.vala

Whenever we select another day than "today" and then click on the calendar icon to reset to "today", the rounded styling of the previously selected day is not removed - despite the fact, that the shown events are from today.
This PR fixes this issue.

Fixed an issue where focus style was not reset to today

---

src/Widgets/calendar/CalendarView.vala

Fixes #283 
Reset position and relative position after rebuilding carousel.
This was forgotten to be done in #280.

Fix incorrect month shown on re-opening indicator if previously changed month (#283)

---

src/Widgets/ComponentRow.vala

Since this is a time you need to take action by, and not a time when something happens, I think it makes it more clear to add a little bit of a distinction beyond the icon here

ComponentRow: Add "due by" for tasks

---

README.md
meson.build

Commit https://github.com/elementary/wingpanel-indicator-datetime/commit/1b8fa36c5a451de2cdad82db07bf569ffe1b8822 started using `Granite.TOOLTIP_SECONDARY_TEXT_MARKUP`, which was only added with granite 6.0.0.
This PR adds a `>= 6.0.0` requirement for granite to `meson.build` and updates `README.md` build dependencies as well. The `deb-packaging` branch might need a similar update.

meson: require granite >= 6.0.0

---

src/Widgets/calendar/GridDay.vala

Use bind_property to make sure that it is synced on creation.
Fixes #303

GridDay: Do not connect to the notify signal for the property
