src/Widgets/calendar/CalendarModel.vala
Fixes `hash_table_get_keys` warnings. It is strongly not recommended to initialize class fields in a thread and using them without knowing if they did really initialize at the usage time. This class would do that almost every time since it calls `load_all_sources` not in the constructor but after creating the class object which is doing initializing in a thread. This branch fixes it.
=> Fix get_keys warning

src/Widgets/calendar/CalendarModel.vala
Reverts and adjusts to @parnold-x suggestions in the #25. I've moved everything but the HashTables to the Thread initialization because of possible performance issues.
=> Revert #25

src/Indicator.vala, src/Services/SettingsManager.vala, src/Services/TimeManager.vala, src/Widgets/PanelLabel.vala, src/Widgets/calendar/Calendar.vala, src/Widgets/calendar/CalendarModel.vala, src/Widgets/calendar/ControlHeader.vala, src/Widgets/calendar/Grid.vala, src/Widgets/calendar/Util.vala
Updates the Free Software Foundation's address in license headers 
Fixes #14
=> Update FSF address. Close #14

src/CMakeLists.txt
Another possible solution for  #43
=> Fix the build system not finding the custom vapi

schemas/CMakeLists.txt, schemas/io.elementary.desktop.wingpanel.datetime.gschema.xml, src/Services/SettingsManager.vala
=> RDNN GSettings

src/Widgets/calendar/ControlHeader.vala
=> Fix datetime format string

src/Widgets/PanelLabel.vala
Fixes #18 
This will look slightly different in American English until after https://github.com/elementary/granite/pull/202 is merged
=> PanelLabel: Show weekday setting

debian/control, debian/rules
=> Update packaging for Meson

src/Indicator.vala
* GObject-style
* Organize
* Remove unnecessary position variable
* `show_settings` is only used once, so just lambda
* ModelButton closes popovers so no need to manually close (twice)
* Reduce variable scope
=> Indicator.vala: misc cleanup, gobject style

data/io.elementary.desktop.wingpanel.datetime.gschema.xml, src/Widgets/PanelLabel.vala
=> Add option for ISO 8601 format

meson.build, src/Event.vala, src/Widgets/calendar/CalendarModel.vala
one class per file
* Use GObject-style construction
* Reduce variable scope
=>  Make Event class its own file

src/Widgets/calendar/Util.vala
None of this appears to be used at all
=> Util: Remove dead CSS

src/Indicator.vala, src/Widgets/calendar/Calendar.vala
MVP version of #126 
Looks like this:
=> Indicator: Display events in their own column

meson.build, po/POTFILES, src/Indicator.vala, src/Widgets/EventRow.vala
This will become more complicated with styling and such as we move towards something that resembles the events sidebar in calendar. Making this its own class as a first step
=> Create EventRow class

data/EventRow.css, data/datetime.gresource.xml, src/Widgets/EventRow.vala
Adds css to match Calendar. Doesn't currently get color from the calendar source. All events show as blue
=> Add EventRow.css

src/Event.vala, src/Indicator.vala, src/Widgets/EventRow.vala, src/Widgets/calendar/CalendarModel.vala
Also rename `day_event` to `is_allday` for clarity
=> Add event row headers

src/Widgets/calendar/Util.vala
=> Util: rewrite ical_to_date_time

src/Widgets/calendar/Grid.vala
And explicitly scope variables and methods
=> Grid: Use GObject-style construction

src/Widgets/calendar/Grid.vala
=> Grid: fix a regression with filling horizontal space

src/Indicator.vala, src/Widgets/calendar/CalendarModel.vala
Might be able to simplify CalendarModel a bit more if we pass the sort function off to the ListBox?
=> Move event sorting from CalendarModel to the ListBox

data/GridDay.css, src/Widgets/calendar/GridDay.vala, src/Widgets/calendar/Util.vala
=> Add dots for events in the calendar

src/DateRange.vala
=> DateRange: remove unused properties and functions

src/Widgets/calendar/CalendarModel.vala
Needs to be tested with someone whose week starts not on Sunday. I see no difference from master here
=> CalendarModel: Use GLib.DateWeekday

src/Widgets/EventRow.vala, src/Widgets/calendar/Util.vala
Remove duplicate util and all that implies
=> EventRow: Simplify assigning color

src/Widgets/calendar/CalendarModel.vala, src/Widgets/calendar/CalendarView.vala, src/Widgets/calendar/Grid.vala, src/Widgets/calendar/GridDay.vala, src/Widgets/calendar/Util.vala
I intentionally left just one error because we're removing the whole line in #190
=> Fix vala-lint errors

data/datetime.appdata.xml.in, src/Widgets/calendar/Util.vala, vapi/libecal-1.2.vapi, vapi/libical.vapi
The exact same fix as https://github.com/elementary/calendar/pull/461
=> Utils: fix several crashes with event processing

data/datetime.appdata.xml.in, meson.build
=> Release 2.2.1

meson.build, src/Widgets/calendar/CalendarModel.vala, src/Widgets/calendar/Util.vala
=> Add support for libecal-2.0

data/datetime.appdata.xml.in, meson.build
=> Release 2.2.2

data/EventRow.css, data/datetime.appdata.xml.in
=> EventRow: Fix appearance in dark style

data/datetime.appdata.xml.in, src/Widgets/calendar/CalendarModel.vala
Fixes #206 
Thanks to @ikarosdev for locating the source of this issue
=> Fix missing event dots

data/datetime.appdata.xml.in, meson.build
This is pretty big performance improvement that I'd like to get in before we break compatibility with bionic/hera
=> Release 2.2.4

src/Widgets/EventRow.vala, src/Widgets/calendar/Util.vala, vapi/libical.vapi
Based on https://github.com/elementary/calendar/pull/515
=> Fix event times with timezones

.github/workflows/main.yml, meson.build, src/Widgets/calendar/CalendarView.vala, src/Widgets/calendar/Grid.vala, src/Widgets/calendar/GridDay.vala, src/Widgets/calendar/Util.vala
=> Use Hdy.Carousel

.github/workflows/release.yml, data/EventRow.css, data/GridDay.css, src/Widgets/calendar/GridDay.vala, src/Widgets/calendar/Util.vala
Supersedes #219 
Supersedes #188 
Requires greenfield
=> Rewrite styles for Greenfield

src/Widgets/PanelLabel.vala
=> PanelLabel: Use tabular numbers font feature to display the time

src/Widgets/calendar/CalendarView.vala
Just a little extra stylish flair
=> CalendarView: Add accent color to month label

src/Indicator.vala
I'm not sure Tasks has a way to launch to the right task list?
=> Indicator: launch Tasks when clicking rows

data/datetime.appdata.xml.in, meson.build
Waiting a couple days for translations
=> Release 2.4.0
